django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponseRedirect

urlpatterns = [
    path('', lambda r: HttpResponseRedirect('polls/')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField('Вопрос', max_length=200)
    publication_date = models.DateTimeField('Дата публикации', default=timezone.now)
    
    class Meta:
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.publication_date <= now
        
    was_published_recently.admin_order_field = 'publication_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Опубликовано недавно?'


class Choice(models.Model):
    choice_text = models.CharField('Текст ответа', max_length=200)
    votes = models.IntegerField('Голоса', default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'ответ'
        verbose_name_plural = 'ответы'

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'last_questions'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            publication_date__lte=timezone.now()
        ).order_by('-publication_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(publication_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Ты не выбрал вариант ответа 🙁',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <title>Голосовалочная</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="mx-auto navbar-brand" href="{% url 'polls:index' %}">Голосовалочная</a>
        </div>
    </nav>
    
    
    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</body>

</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="row mt-3">
        <div class="col-12 mx-auto text-center">
            <h1 class="h3">{{ question.question_text }}</h1>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-5 mx-auto">
            {% if error_message %}
            <div class="alert alert-danger text-center" role="alert">
                {{ error_message }}
            </div>
            {% endif %}            
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'polls:vote' question.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {% for choice in question.choice_set.all %}
                            <div class="form-check mb-1">
                                <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                <label class="form-check-label" for="choice{{ forloop.counter }}">
                                    {{ choice.choice_text }}
                                </label>
                            </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Проголосовать <i class="fas fa-check"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="row mt-3">
        <div class="col-5 mx-auto text-center">
            <h1 class="h3">Доступные опросы</h1>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-5 mx-auto">
            {% if last_questions %}
            <div class="list-group">
                {% for question in last_questions %}
                <a href="{% url 'polls:detail' question.id %}" class="list-group-item list-group-item-action">
                    <div class="d-flex justify-content-between align-items-center">
                        {{ question.question_text }}
                        <i class="text-primary fas fa-chevron-circle-right"></i>
                    </div>
                </a>
                {% endfor %}
            </div>
            {% else %}
            <div class="alert alert-info text-center" role="alert">
                Вопросов пока нет 🙃
            </div>
            {% endif %}  
        </div>
    </div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="row mt-3">
        <div class="col-12 mx-auto text-center">
            <h1 class="h3">{{ question.question_text }}</h1>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-5 mx-auto">
            <ul class="list-group">
                {% for choice in question.choice_set.all %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between align-items-center">
                            {{ choice.choice_text }}
                        <span class="badge badge-primary badge-pill">{{ choice.votes }}</span>    
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-5 mx-auto text-center">
            <a role="button" class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Хочешь еще?</a>
        </div>
    </div>
            

{% endblock %}